# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'StringCalculator.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './StringCalculator.sln'
    arguments: '-c Release --no-restore'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './StringCalculator.sln'
    arguments: '-c Release --no-restore --no-build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './StringCalculator/StringCalculator.csproj'
    arguments: '-c Release -o out --no-restore --no-build'